"""Loaders shared by every page. Cached, so switching pages does not recompute.

Where the data comes from, in order:
  1. MACRO_REGIME_DATA_URL set: a snapshot published by `ingest.py publish`.
     This is how the hosted app gets real data it cannot fetch itself.
  2. Otherwise MACRO_REGIME_DB (default data/regime.duckdb), a local store,
     seeded with demo data only if MACRO_REGIME_SEED_DEMO=1 and it is empty.
"""

from __future__ import annotations

import datetime as dt
import os
import tempfile
from pathlib import Path

import streamlit as st

from src.drivers import compute, load_config
from src.regimes import load_regimes, run
from src.store import Store

INDICATORS = "config/indicators.yml"
REGIMES = "config/regimes.yml"
REPO_URL = "https://github.com/su198-hub/macro-regime"
SNAPSHOT_CHECK_SECONDS = 600


def data_url() -> str | None:
    return os.environ.get("MACRO_REGIME_DATA_URL") or None


@st.cache_data(ttl=SNAPSHOT_CHECK_SECONDS, show_spinner=False)
def snapshot_manifest() -> dict | None:
    """The published snapshot's manifest, or None if not configured or unreachable."""
    url = data_url()
    if not url:
        return None
    from src.snapshot import read_manifest
    try:
        return read_manifest(url)
    except Exception:
        return None


def data_version() -> str:
    """Changes whenever a new snapshot is published, so caches rebuild."""
    m = snapshot_manifest()
    return m["published_at"] if m else "local"


@st.cache_resource(show_spinner="Loading the latest published data…", max_entries=1)
def _store_for(version: str):
    if version != "local":
        from src.snapshot import load_snapshot
        safe = version.replace(":", "").replace("+", "_")
        path = Path(tempfile.gettempdir()) / "macro-regime" / f"snapshot-{safe}.duckdb"
        try:
            return load_snapshot(data_url(), path)
        except Exception as exc:
            st.warning(f"Could not load the published data ({exc}). Showing local data instead.")

    # Point MACRO_REGIME_DB outside OneDrive; sync locks the file mid-write.
    store = Store(os.environ.get("MACRO_REGIME_DB", "data/regime.duckdb"))
    # Hosted deploys start from an empty disk. Opt-in only, so synthetic data
    # never lands in a real store by accident.
    if os.environ.get("MACRO_REGIME_SEED_DEMO") == "1" and store.coverage().empty:
        from ingest import load_demo
        load_demo(store, load_config(INDICATORS))
    return store


def get_store():
    return _store_for(data_version())


@st.cache_data(ttl=900)
def _results_for(vintage: dt.date, version: str):
    store = _store_for(version)
    cfg = load_config(INDICATORS)
    reg = load_regimes(REGIMES)
    res = compute(store, cfg, vintage)
    if res["drivers"].empty:
        return None
    res.update(run(res["drivers"], reg), config=cfg, regimes=reg)
    return res


def get_results(vintage: dt.date):
    return _results_for(vintage, data_version())


def is_demo(store) -> bool:
    return "demo" in store.sources()


def published_note() -> str:
    """'Data published 15 September 2026 at 07:23 UTC' on a snapshot, else ''.

    The time matters: a second publish on the same day otherwise looks
    identical, and there is no way to tell the app has picked it up.
    """
    m = snapshot_manifest()
    if not m:
        return ""
    when = dt.datetime.fromisoformat(m["published_at"]).astimezone(dt.timezone.utc)
    return (f"Data published {when:%d %B %Y} at {when:%H:%M} UTC, "
            f"latest vintage {m['latest_vintage']}.")


def refresh_button() -> None:
    """Let a viewer skip the wait for the periodic snapshot check."""
    if not data_url():
        return
    if st.button("Check for new data", icon=":material/refresh:", type="tertiary"):
        snapshot_manifest.clear()
        st.rerun()


def source_sentence(vendors: set[str]) -> str:
    """Plain-language data source, as HTML, for footers and the methodology."""
    parts = []
    if "demo" in vendors:
        return ("Synthetic demo series generated by <code>ingest.py demo</code>, with "
                "invented dynamics, so the numbers mean nothing.")
    if "macrobond" in vendors:
        parts.append("Macrobond, carrying each series from its original publisher: BEA, "
                     "BLS, Census, the Federal Reserve Board, the Chicago and Cleveland Feds, "
                     "CBO, OMB and the University of Michigan")
    if "fred" in vendors:
        parts.append("FRED and ALFRED, Federal Reserve Bank of St. Louis")
    if not parts:
        return "No data loaded."
    return "; ".join(parts) + ". Each value is the latest vintage published on or before the chosen date."
