# Sabon Next LT is a licensed face and is not bundled. It renders where it is
# installed; everyone else falls back to Georgia.

[theme]
base = "light"
font = "Arial, Helvetica, sans-serif"
headingFont = "'Sabon Next LT', 'Sabon LT Pro', 'Sabon LT Std', Sabon, Georgia, 'Times New Roman', serif"
primaryColor = "#111111"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f3f3"
textColor = "#111111"
borderColor = "#dcdcdc"
linkColor = "#111111"
baseRadius = "3px"

[client]
toolbarMode = "viewer"
